-- MySQL dump 10.13  Distrib 8.0.23, for Win64 (x86_64)
--
-- Host: localhost    Database: rti-baza
-- ------------------------------------------------------
-- Server version	8.0.23

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `subjects`
--

DROP TABLE IF EXISTS `subjects`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `subjects` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `department` int DEFAULT NULL,
  `semester` int DEFAULT NULL,
  `espb` int DEFAULT NULL,
  `type` int DEFAULT NULL,
  `lectures` float DEFAULT NULL,
  `exc` float DEFAULT NULL,
  `lab` float DEFAULT NULL,
  `goal` text,
  `result` text,
  `lectureWhen` varchar(255) DEFAULT NULL,
  `excWhen` varchar(255) DEFAULT NULL,
  `comment` text,
  `examVisible` tinyint(1) DEFAULT NULL,
  `labVisible` tinyint(1) DEFAULT NULL,
  `projectVisible` tinyint(1) DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=76 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `subjects`
--

LOCK TABLES `subjects` WRITE;
/*!40000 ALTER TABLE `subjects` DISABLE KEYS */;
INSERT INTO `subjects` VALUES (3,'13E111PP1','Praktikum iz programiranja 1',1,1,2,2,0,0,2,'Osnovna namena Praktikuma je upoznavanje studenata sa kompletnim procesom razvoja programa i osposobljavanje za samostalan rad u konkretnom razvojnom okruženju. Ovako koncipiran, predmet ima za cilj da obradi i praktično nauči studente praktičnoj primeni svega onoga što su imali prilike da čuju na nastavi iz predmeta Programiranje 1.','Znanje osnovnih koncepata rada sa razvojnim okruženjima (izvršavanje programa korak po korak, praćenje trenutnog sadržaja promenljivih, preusmeravanje ulaza i izlaza), iz čega sledi osposobljenost za samostalno rešavanje programskih problema male ili srednje složenosti na računaru. Praktična primena svega naučenog u okviru predmeta Programiranje 1.','','','Demonstracioni časovi predstavljaju prikaz rada u razvojnom okruženju. Domaći zadaci se periodično zadaju studentima, tako da imaju dovoljno vremena da se pripreme za odbranu na laboratorijskim vežbama. Prilikom odbrane domaćeg zadatka, ispitivač proverava i znanje studenata iz oblasti obuhvaćenih domaćim zadatkom. Ispit podrazumeva praktičnu izradu programa srednje složenosti na računaru.',1,1,1,'2021-02-12 14:22:21','2021-02-12 14:22:21');
INSERT INTO `subjects` VALUES (5,'13E111ORT','Osnovi računarske tehnike',1,2,5,1,3,2,0,'Upoznavanje sa Bulovom algebrom, prekidačkim funkcijama, prekidačkim mrežama, logičkim i memorijskim elementima i kombinacionim i sekcencijalnim modulima.','Po završetku kursa studenti će biti sposobni da: razumeju strukturu prekidačkih mreža; obavljaju analizu i sintezu kombinacionih i sekvencijalnih mreža; koriste kombinacione i sekvencijalne module.','P1 Ponedeljak 14:00 P2 Utorak 14:00','V1 Utorak 14:00 V2 Sreda 14:00','',1,1,1,'2021-02-12 15:13:52','2021-02-17 18:41:51');
INSERT INTO `subjects` VALUES (6,'13E111POT','Praktikum iz osnova računarske tehnike',1,2,2,2,0,0,2,'Upoznavanje studenata sa osnovnim kombinacionim i sekvencijalnim elementima. Razumevanje strukture i funkcionisanja prekidačkih mreža. Realizacija složenih prekidačkih mreža pomoću vizuelnog simulatora.','Po završetku kursa studenti će biti sposobni da: razumeju strukturu prekidačkih mreža; obavljaju analizu i sintezu kombinacionih i sekvencijalnih mreža; koriste kombinacione i sekvencijalne module.','','','POT hehe',1,1,1,'2021-02-12 15:15:06','2021-02-12 15:15:06');
INSERT INTO `subjects` VALUES (7,'13E111PP2','Praktikum iz programiranja 2',1,2,2,2,0,0,2,'Osnovna namena Praktikuma je upoznavanje studenata sa kompletnim procesom razvoja programa i osposobljavanje za samostalan rad u konkretnom razvojnom okruženju. Ovako koncipiran, predmet ima za cilj da obradi i praktično nauči studente svemu onome što su imali prilike da čuju na nastavi iz predmeta Programiranje 2.','Znanje osnovnih koncepata rada sa razvojnim okruženjima (izvršavanje programa korak po korak, praćenje trenutnog sadržaja promenljivih, preusmeravanje ulaza i izlaza), iz čega sledi osposobljenost za samostalno rešavanje programskih problema male ili srednje složenosti. Praktična primena naučenog iz predmeta Programiranje 2.','','','CcCcC',1,1,1,'2021-02-12 15:16:20','2021-02-12 15:16:20');
INSERT INTO `subjects` VALUES (8,'13E112ASP','Algoritmi i strukture podataka',1,3,6,1,3,2,0,'Upoznavanje sa logičkom organizacijom i memorijskom reprezentacijom linearnih i nelinearih struktura podataka, osnovnim operacijama i tipičnim primenama ovih struktura. Upoznavanje sa algoritmima i odgovarajućim strukturama podataka koje se koriste za pretraživanje i sortiranje, kao i njihovom praktičnom implementacijom u programskim jezicima.','Ovaj predmet treba studenta da osposobi za programsku implementaciju linearnih i nelineranih struktura, kao i algoritama za rad sa njima u tipičnim primenama. Pored toga, predmet treba studenta da osposobi za praktičnu implementaciju algoritama pretraživanja i sortiranja u programskim jezicima i rešavanje praktičnih problema.','P1 Sreda 10:00\nP2 Sreda 12:00','V1 Petak 12:00\nV2 Petak 14:00','ASP Komentar',1,1,1,'2021-02-12 20:55:56','2021-02-12 20:55:56');
INSERT INTO `subjects` VALUES (10,'13E111P2','Programiranje 2',1,2,6,1,3,2,0,'Upoznavanje sa sintaksom i semantikom programskog jezika C. Primena naprednih koncepata proceduralnog programiranja u jeziku C. Osposobljavanje studenata za konstrukciju algoritama, korišćenje statičkih i dinamičkih struktura podataka, implementaciju i testiranje programa u jeziku C.','Studenti će biti u stanju da: transformišu izraze Bulove algebre, izračunaju vrednost broja na osnovu prikaza u komplementu dvojke i računaju sa ovakvim brojevima, napišu jednostavan program na simboličkom mašinskom jeziku picoComputer-a, razumeju sintaksne definicije, razvijaju, isprave i testiraju modularne strukturirane programe na višem programskom jeziku i procene njihovu kompleksnost.','P1 Ponedeljak 12:00\nP2 Utorak 12:00','V1 Utorak 14:00\nV2 Sreda 14:00','',0,0,1,'2021-02-13 09:05:27','2021-02-17 19:00:05');
INSERT INTO `subjects` VALUES (11,'13E112OO1','Objektno-orijentisano programiranje 1',1,3,6,1,2,2,1,'Razumevanje i ovladavanje osnovnim principima objektno-orijentisanog programiranja, kao što su apstrakcija, kapsulacija, nasleđivanje i polimorfizam. Razumevanje koncepata izuzetaka i šablona. Sticanje veštine objektno-orijentisanog programiranja na jeziku C++ . Korišćenje standardne biblioteke šablona (STL).','Po uspešno savladanom predmetu, studenti će biti osposobljeni da: - interpretiraju i primenjuju paradigmu objektno-orijentisanog programiranja; - demonstriraju principe objektno-orijentisanog programiranja na jeziku C++; - rešavaju praktične probleme na jeziku C++; - koriste standardnu biblioteku šablona (STL).','','','Predavanja i auditorne vežbe se drže uz elektronske prezentacije. Na predavanjima se uvode koncepti OO programiranja i daje definicija jezika C++, dok se na auditornim vežbama demonstriraju praktični primeri objektno-orijentisanog programiranja na jeziku C++. Laboratorijske vežbe su podeljene na pokazne i kontrolne.',1,1,1,'2021-02-14 19:34:11','2021-02-14 19:34:11');
INSERT INTO `subjects` VALUES (12,'13E112ORT2','Osnovi računarske tehnike 2',1,3,6,1,2,2,1,'Upoznavanje sa postupcima projektovanja digitalnih sistema, strukturom računara, i elementima arhitekture i organizacije procesora.','Po završetku kursa studenti će biti sposobni da razumeju: postupak projektovanja digitalnih sistema; strukturu računara; elemente arhitekture i organizacije računara.','','','',1,1,1,'2021-02-14 19:35:12','2021-02-14 19:35:12');
INSERT INTO `subjects` VALUES (13,'13E112AR','Arhitektura računara',1,4,6,1,2,2,1,'Upoznavanje sa konceptima CISC i RISC arhitekture, i strukturom magistrale, ulazno/izlaznog sistema i sistema diskova.','Po završetku kursa studenti će biti sposobni da: razumeju strukturu i funkcionisanje procesora SICS i RISC, magistrale, ulazno/izlaznog sistema i sistema diskova; koriste literaturu radi daljeg izučavanja ovih oblasti.','','','',1,1,1,'2021-02-14 19:36:10','2021-02-14 19:36:10');
INSERT INTO `subjects` VALUES (14,'13E112OO2','Objektno-orijentisano programiranje 2',1,4,6,1,2,2,1,'Razumevanje i ovladavanje naprednim konceptima objektno-orijentisanog programiranja, kao i osnovnim konceptima konkurentnog i događajima vođenog programiranja, uz njihovu primenu na jezicima Java i C#. Ovladavanje elementima programiranja višenitnih aplikacija sa grafičkim korisničkim interfejsom. Razumevanje koncepata platforme .NET.','Student poznaje napredne koncepte OO programiranja i osnovne koncepte konkurentnog i događajima vođenog programiranja. Student je sposoban da razvija objektno-orijentisane višenitne aplikacije sa grafičkim korisničkim interfejsom na jeziku Java. Student poznaje elemente višejezičke .NET platforme i jezika C#.','','','Predavanja i auditorne vežbe se drže uz elektronske prezentacije. Na predavanjima se uvode koncpeti i izlaže definicija jezika Java i C#, dok se na auditornim vežbama demonstriraju praktični primeri objektno-orijentisanog programiranja na jezicima Java i C#. Laboratorijske vežbe su podeljene na pokazne i kontrolne.',1,1,1,'2021-02-14 19:36:50','2021-02-14 19:36:50');
INSERT INTO `subjects` VALUES (15,'13E112OS1','Operativni sistemi 1',1,4,6,1,2,2,1,'Upoznati studente sa namenom i funkcijama operativnih sistema, kao i osnovnim principima funkcionisanja, projektovanja i implementacije operativnih sistema.','Steći osnovna znanja o konceptima, algoritmima, principima, problemima i rešenjima vezanim za operativne sisteme uopšte, nevezano ni za jedan konkretan operativni sistem. Osposobiti studente da razumeju i koriste postojeće sisteme, kao i da samostalno projektuju i realizuju sopstvene specijalizovane sisteme.','','','PPPPPPPPPPPProjekat',1,1,1,'2021-02-14 19:37:46','2021-02-14 19:37:46');
INSERT INTO `subjects` VALUES (16,'13E112RM1','Računarske mreže 1',1,4,6,1,2,2,1,'Upoznavanje studenata sa osnovnim konceptima savremenih računarskih mreža i komunikacionih protokola.','Predmet nudi široku predstavu računarskih mreža uopšte, bazirano na komunikacionim protokolima na različitim nivoima (od nižeg ka višem). Savladavanjem znanja iz ovog predmeta, studenti dobijaju jasnu sliku funkcionisanja računarskih mreža od fizičkog do aplikativnog nivoa.\n','','','',1,1,1,'2021-02-14 19:38:42','2021-02-14 19:38:42');
INSERT INTO `subjects` VALUES (17,'13E112POS','Praktikum iz operativnih sistema',1,4,3,2,0,1,0.5,'Kroz praktičan rad na operativnom sistemu Linux, upoznati studente sa osnovnim tehnikama i postupcima vezanim za korišćenje i administraciju ovog operativnog sistema.','Kroz praktičan rad na operativnom sistemu Linux, osposobiti studente da koriste i (na elementarnom nivou) administriraju operativni sistem Linux.','','','',1,1,1,'2021-02-14 19:39:28','2021-02-14 19:39:28');
INSERT INTO `subjects` VALUES (18,'13E113AOR1','Arhitektura i organizacija računara 1',1,5,6,1,2,2,1,'Upoznavanje sa konceptima hijerarhijskog memorijskog sistema, RISC arhitekturom i pipeline organizacijom.\n','Po završetku kursa studenti će biti sposobni da: razumeju strukturu i funkcionisanje hijerarhijskog memorijskog sistema; razumeju RISC arhitekturu i osnovne koncepte pipeline organizacije; koriste literaturu radi daljeg izučavanja ovih oblasti.\n','','','',1,1,1,'2021-02-14 19:40:40','2021-02-14 19:40:40');
INSERT INTO `subjects` VALUES (19,'13E113BP1','Baze podataka 1',1,5,6,1,2,2,1,'1. Upoznavanje studenata sa osnovnim pojmovima i principima Sistema za Upravljanje Bazama Podataka. 2. Upoznavanje sa osnovnim konceptima projektovanja baza podataka. 3. Osposobljavanje studenata za dizajn i implementaciju konkretne baze podataka i korišćenje komercijalnih sistema za upravljanje bazama podataka.\n','Osposobljenost studenata za dizajn i implementaciju konkretne baze podataka i korišćenje komercijalnih sistema za upravljanje bazama podataka.\n','','','30 časova predavanja + 30 časova vežbi na tabli sa rešavanjem zadataka + 15 časova laboratorijskih vežbi, kolokvijum na sredini semestra, projekat. Ukupno 75 časova samostalnog učenja i vežbanja, od čega 3 časa nedeljno tokom semestra i približno 30 časova pripreme u ispitnom roku.\n',1,1,1,'2021-02-14 19:41:20','2021-02-14 19:41:20');
INSERT INTO `subjects` VALUES (20,'13E113KDP','Konkurentno i distribuirano programiranje',1,5,6,1,2,2,1,'Upoznavanje studenata sa osnovnim konceptima konkurentnog i distribuiranog programiranja. Uvođenje pojma različitih nivoa apstrakcije u konkurentnom i distribuiranom programiranju. Osposobljavanje studenata za pisanje konkurentnih i distribuiranih programa za najčešće probleme u različitim programskim jezicima.\n','Posedovanje osnovnih znanja o konceptima, algoritmima, principima, problemima i rešenjima vezanim za konkurentno i distribuirano programiranja. Prepoznavanje različitih nivoa apstrakcije u konkurentnom i distribuiranom programiranju. Osposobljenost studenta da u jeziku Java samostalno pišu jednostavne konkurentne i distribuirane aplikacije i da samostalno rešava najčešće probleme sinhronizacije.\n','','','',1,1,1,'2021-02-14 19:42:16','2021-02-14 19:42:16');
INSERT INTO `subjects` VALUES (21,'13E113OS2','Operativni sistemi 2',1,5,6,2,2,2,1,'Upoznati studente sa širim spektrom složenijih i naprednijih koncepata i principa konstrukcije operativnih sistema. Obezbediti napredna znanja o konceptima, algoritmima, principima, problemima i rešenjima vezanim za operativne sisteme uopšte. Upoznati se sa principima konstrukcije konkretnih, realnih operativnih sistema\n','Poznavanje opštih principa rada, konstrukcije i implementacije operativnih sistema uopšte. Poznavanje naprednijih koncepata i algoritama. Poznavanje nekih delova i rešenja iz konkretnih popularnih operativnih sistema opšte namene.\n','','','PPPPPPPPPProjekat part2',1,1,1,'2021-02-14 19:43:05','2021-02-14 19:43:05');
INSERT INTO `subjects` VALUES (22,'13E113PPK','Praktikum iz poslovne komunikacije i prezentacije',1,5,3,2,1,1,0.5,'Upoznavanje sa konceptima poslovne komunikacije na nivou organizacija, nivou pojedinca i organizacije, kao i na nivou pojedinaca međusobno.','Po završetku kursa studenti će biti sposobni da razumeju poslovnu komunikaciju neophodnu za rad na poslovnim projektima, kao i svakodnevnim aktivnostima prilikom rada u okviru tima. Studenti će tako steći potrebna znanja da izraze svoje stavove, planove, sposobnosti i potrebe u pisanoj i oralnoj formi.','','','',1,1,1,'2021-02-14 19:56:31','2021-02-14 19:56:31');
INSERT INTO `subjects` VALUES (23,'13E113PIA','Programiranje internet aplikacija',1,6,6,1,2,2,1,'Upoznavanje studenata sa osnovnim pojmovima razvoja višeslojnih Internet aplikacija baziranih na programskom jeziku Java (Java servlets, JSP, JSF framework). Primena najsavremenijih tehnologija za dizajn i implementaciju komercijalnih Internet aplikacija.','Studenti će biti osposobljeni da projektuju i razviju višeslojne Internet aplikacije potrebne složenosti koristeći najefikasnije metode i tehnologije. Kroz sadržaj kursa upoznaće se i sa vrstama Internet aplikacija, kao i sa osnovama Veb dizajna.\n','','','',1,1,1,'2021-02-14 19:57:49','2021-02-26 12:01:00');
INSERT INTO `subjects` VALUES (24,'13E113ZP','Zaštita podataka',1,6,6,1,2,2,1,'Upoznavanje studenata sa osnovnim konceptima zaštite podataka. Razumevanje osnova kriptografije i sigurnosnih protokola. Upoznavanje sa rizicima u mrežnom okruženju i upoznavanje sa svim nivoima na kojima mere zaštite treba da budu uvedene.\n','Studenti će steći znanja o načinima za odvraćanje, detekciju, sprečavanje i neutralisanje narušavanja sigurnosti.\n','','','30 časova predavanja, 30 časova vežbi na tabli, 15 časova praktičnih vežbi u laboratoriji. Približno 70 sati samostalnog učenja i vežbanja.\n',1,1,1,'2021-02-14 19:59:03','2021-02-14 19:59:03');
INSERT INTO `subjects` VALUES (25,'13E113SS','Sistemski softver',1,6,6,1,2,2,1,'Osnove asemblerskog programiranja x86 i ARM procesorskih arhitektura. Upoznavanje sa funkcijama i načinom konstrukcije različitih sistemskih alata, kao što su makro procesori, asembleri, emulatori, povezivači i punioci.','Osposobljavanje studenata da razumeju funkciju i načine konstrukcije različitih sistemskih alata, kao što su makro procesori, asembleri, emulatori, povezivači i punioci. Studenti treba da budu u stanju da i sami konstruišu i implementiraju slične alate ili prilagode već postojeće. Studenti se upoznaju sa osnovama asemblerskog programiranja.','','','',1,1,1,'2021-02-14 19:59:44','2021-02-14 19:59:44');
INSERT INTO `subjects` VALUES (26,'13E113AOR2','Arhitektura i organizacija računara 2',1,6,6,2,2,2,1,'Procesor. CISC arhitektura. Faze izvršavanja instrukcija. Organizacija. Operaciona jedinica sa direktnim vezama i jednom, dve i tri magistrale. Upravljačka jedinica - ožičena i mikroprogramska sa različitim načinima kodiranja signala. Simulator. Pregled. Mogućnosti. Vizuelna simulacija. Struktura simulatora. Prikazivanje signala i stanja. Simulacija prekidačkih mreža. Realizacija asemblera.','Procesor. CISC arhitektura. Faze izvršavanja instrukcija. Organizacija. Operaciona jedinica sa direktnim vezama i jednom, dve i tri magistrale. Upravljačka jedinica - ožičena i mikroprogramska sa različitim načinima kodiranja signala. Simulator. Pregled. Mogućnosti. Vizuelna simulacija. Struktura simulatora. Prikazivanje signala i stanja. Simulacija prekidačkih mreža. Realizacija asemblera.','','','',1,1,1,'2021-02-14 20:00:25','2021-02-14 20:00:25');
INSERT INTO `subjects` VALUES (27,'13E113USP','Upravljanje softverskim projektima',1,6,6,2,2,2,1,'Upoznavanje studenata sa osnovnim pojmovima u softverskoj industriji i realizacija jednog velikog timskog projekta od faze analize korisničkih zahteva do faze isporuke softvera. Upravljanje projektima na tradicionalan način i agilne metodologije (DSDM, Scrum, Extreme programming,...).','Nakon odslušanog predmeta studenti će biti osposobljeni za analizu korisničkih zahteva, pisanje ponude za izradu softvera, pisanje plana po fazama i razvoj samog softvera, upravljanje softverskim projektom od početka razvojnog procesa do kraja i pisanje korisničke dokumentacije.','','','Predavanja, auditorne vežbe, laboratorijske vežbe i rad na praktičnom projektu tokom celog semestra.',1,1,1,'2021-02-14 20:01:10','2021-02-14 20:01:10');
INSERT INTO `subjects` VALUES (28,'13E114MIPS','Mikroprocesorski sistemi',1,7,6,1,2,2,1,'Upoznavanje sa naprednim mogućnostima savremenih mikroprocesora (eksploatacija paralelizma na nivou instrukcija, predviđanje skokova, predviđanje podataka, hardverska podrška za izvršavanje više niti, i podrška za SMP i DSM sisteme) i ovladavanje tehnikama projektovanja i programiranja mikroprocesorskih sistema.','Očekuje se da će studenti nakon ovoga kursa biti sposobni da: - za zadati problem osmisle i dizajniraju potrebni hardver, - za dati hardverski dizajn i opis problema osmisle i isprogramiraju potrebni softver, - za nove komponente znaju samostalno da prouče dokumentaciju do nivoa potrebnog za korišćenje komponenata u sistemu.','','','',1,1,1,'2021-02-14 20:02:12','2021-02-14 20:02:12');
INSERT INTO `subjects` VALUES (29,'13E114PP1','Programski prevodioci 1',1,7,6,1,2,2,1,'Cilj predmeta je upoznavanje studenata sa osnovnim pojmovima teorije formalnih jezika, sa osnovnim tehnikama konstrukcije jezičkih procesora, kompajlera i interpretatora i osposobljavanje studenata za upotrebu standardnih alata za konstrukciju jezičkih procesora i kompajlera.','Očekuje se da student po završetku kursa bude u stanju da: Demonstrira razumevanje, kritičku analizu i primenu važećih teorija, modela i tehnika iz oblasti konstrukcije programskih prevodilaca. Da bude u stanju da na formalan način opiše sintaksu jezika i primenom standarnih alata konstruiše jednostavnije jezičke procesore i translatore.','','','',1,1,1,'2021-02-14 20:02:59','2021-02-14 20:02:59');
INSERT INTO `subjects` VALUES (30,'13E114VLSI','Računarski VLSI sistemi',1,7,6,1,2,2,1,'Upoznavanje studenata sa principima projektovanja računarskih VLSI sistema. Upoznavanje sa jezicima za opis hardvera.','Očekuje se da će studenti razviti sposobnost da samostalno dizajniraju računarske VLSI sisteme.','','','',1,1,1,'2021-02-14 20:03:35','2021-02-14 20:03:35');
INSERT INTO `subjects` VALUES (31,'13E114RM2','Računarske mreže 2',1,7,6,2,2,2,1,'Upoznavanje studenata sa arhitekturom i mehanizmima funkcionisanja Interneta, te naprednim konceptima, protokolima i algoritmima funkcionisanja nekih ključnih Internet servisa i savremenih računarskih mreža.','Nakon ovog kursa studenti će u potpunosti razumeti arhitekturu Interneta i modernih mehanizama prosleđivanja paketa. Biće sposobni da samostalno odrede politiku rutiranja i da je implementiraju na realnim mrežnim uređajima. Takođe, kroz učenje o mehanizmima upraljanja uređajima i različitim Internet protokolima biće u stanju da dizajniraju efikasne servise zasnovane na modernim mrežnim tehnologijama.','','','',1,1,1,'2021-02-14 20:04:13','2021-02-14 20:04:13');
INSERT INTO `subjects` VALUES (32,'13E114PS','Projektovanje softvera',1,7,6,2,2,2,1,'Razumevanje i ovladavanje konceptima modeliranja i projektovanja softvera korišćenjem projektnih uzoraka. Učenje standardne grafičke notacije za modeliranje UML kroz 13 vrsta dijagrama, kao i najčešće korišćenih projektnih uzorka strukture, ponašanja i kreiranja.','Student poznaje koncepte modeliranja i projektovanja softvera. Student je sposoban je da modelira složene softverske sisteme koristeći standardni jezik UML 2. Student pri projektovanju softvera ume da prepozna uslove za primenu i da primeni adekvatne projektne uzorke iz GoF kataloga projektnih uzoraka.','','','Predavanja i auditorne vežbe se drže uz elektronske prezentacije. Na predavanjima se uvode koncepeti projektovanja softvera i izlaže notacija UML, kao i konkretni projektni uzorci, dok se na auditornim vežbama demonstriraju praktični primeri modeliranja uz primenu projektnih uzoraka. Laboratorijske vežbe su podeljene na pokazne i kontrolne.',1,1,1,'2021-02-14 20:04:48','2021-02-14 20:04:48');
INSERT INTO `subjects` VALUES (33,'13E114IS','Inteligentni sistemi',1,7,6,2,2,2,1,'Upoznavanje studenata sa osnovnim konceptima i tehnikama veštačke inteligencije i ekspertskih sistema. Tokom kursa studenti će izučavati najpopularnije modele implementacije ovakvih vrsta aplikacija.','Studenti će biti osposobljeni da prepoznaju problem koji pripada oblasti veštačke inteligencije i ekspertskih sistema i da na osnovu svog znanja primene najpodesniju i najefikasniju metodu za njegovo rešavanje.','','','Predavanja, prezentacije, auditorne vežbe, samostalna izrada projekta, laboratorijske vežbe sa vizuelnim simulacijama',1,1,1,'2021-02-14 20:05:32','2021-02-14 20:05:32');
INSERT INTO `subjects` VALUES (34,'13E114PRS','Performanse računarskih sistema',1,8,6,1,2,2,1,'Učenje osnovnih koncepata analize računarskih performansi i oblasti njihove primene. Prikaz pojednostavljenih modela komponenata računarskog sistema (procesori, memorije, diskovi). Osposobljavanje studenata za modeliranje i analizu računarskih sistema i mreža pomoću stohastičkih metoda i analize srednjih vrednosti (MVA) korišćenjem otvorenih i zatvorenih mreža sa redovima za čekanje.','Studenti će biti u stanju da: odaberu odgovarajuću tehniku modeliranja u zavisnosti od karakteristika računarske komponente ili sistema, postave apstraktan model, navedu pretpostavke i aproksimacije za konkretan model, izračunaju indikatore performansi sistema na osnovu datih parametara, kritički diskutuju dobijene numeričke pokazatelje performansi pri interpretaciji rezultata analize.','','','Predavanja, vežbe na tabli, samostalan rad studenata na izradi domaćih zadataka i projekata.',1,1,1,'2021-02-14 20:06:11','2021-02-14 20:06:11');
INSERT INTO `subjects` VALUES (35,'13E114BP2','Baze podataka 2',1,8,6,2,2,2,1,'Učenje XML-a. Fizički dizajn objektno relacionih baza podataka. Učenje različitih mehanizama pristupa i integracije baze.','Ovladavanje XML-om, metodologijom i alatima za fizički dizajn i implementaciju objektno relacionih baza podataka i razumevanje potrebe za različitim mehanizmima pristupa i integracije baze i ovladavanje njihovim korišćenjem.','','','30 časova predavanja + 30 časova vežbi na tabli sa rešavanjem zadataka + 15 časova laboratorijskih vežbi, kolokvijum na sredini semestra, projekat. Ukupno 75 časova samostalnog učenja i vežbanja, od čega 3 časa nedeljno tokom semestra i približno 30 časova pripreme u ispitnom roku.',1,1,1,'2021-02-14 20:07:33','2021-02-14 20:07:33');
INSERT INTO `subjects` VALUES (36,'13E114IS1','Informacioni sistemi 1',1,8,6,2,2,2,1,'Razumevanje značaja i karakteristika informacionih sistema. Uvođenje u tradicionalni razvoj informacionih sistema. Uvođenje u objekno-orijentisani razvoj informacionih sistema.','Znanje iz tradicionalnog razvoja informacionih sistema. Znanje iz objektno-orijentisanog razvoja informacionih sistema.','','','',1,1,1,'2021-02-14 20:08:32','2021-02-14 20:08:32');
INSERT INTO `subjects` VALUES (37,'13E114IEP','Infrastruktura za elektronsko poslovanje',1,8,6,2,2,2,1,'Upoznavanje sa konceptima elektronskog poslovanja i elementima potrebne hardversko softverske infrastrukture.','Po završetku kursa studenti će biti sposobni da: razumeju neophodnu hardversku i softversku infrastrukturu, poslovne modele i bezbedonosne pretnje u sistemima za elekttronsko poslovanje.','','','',1,1,1,'2021-02-14 20:09:08','2021-02-14 20:09:08');
INSERT INTO `subjects` VALUES (38,'13E114MUPS','Multiprocesorski sistemi',1,8,6,2,2,2,1,'Upoznavanje sa osnovnim konceptima paralelnih računarskih sistema i principa paralelnog programiranja. Detaljno upoznavanje sa arhitekturama multiprocesorskih sistema sa zajedničkom memorijom.','Ovaj predmet treba da osposobi studenta da razume projektne odluke u oblasti paralelnih sistema, da koristi simulatore za evaluaciju ovih odluka, kao i da praktično primenjuje principe paralelnog programiranja korišćenjem različitih paralelnih programskih modela.','','','',1,1,1,'2021-02-14 20:09:43','2021-02-14 20:09:43');
INSERT INTO `subjects` VALUES (39,'13E114PAR','Paralelni računarski sistemi',1,8,6,2,2,2,1,'Razumevanje u ograničenjima paralelnog izvršavanja, paralelizma na instrukcijskom nivou, paralelizma u okviru petlji i detekcija izvršavanja paralelizma u realnom vremenu i implementacija paralelizma u hardveru.','Duboko poznavanje rada superskalarnih i procesora sa veoma širokom instrukcijskom reči, optimizacionih delova kompajlera i modela paralelizma','','','',1,1,1,'2021-02-14 20:10:25','2021-02-14 20:10:25');
INSERT INTO `subjects` VALUES (40,'13E114RG','Računarska grafika',1,8,6,2,2,2,1,'Razumevanje i ovladavanje principima računarske 2D i 3D grafike i animacije. Upoznavanje sa tehnologijama grafičkih uređaja, učenje grafičkih transformacija, projekcija, predstavljanja boje, senčenja i animacije, kao i često korišćenih algoritama u računarskoj grafici, grafičkih 2D paketa SRGP i Java 2D, odnosno 3D paketa SPHIGS i OpenGL.','Nakon uspešno savladanog kursa, studenti će biti sposobni da: - opišu principe rada uređaja koji se koriste u računarskoj grafici; - interpretiraju i primenjuju najvažnije algoritme računarske grafike; - kreiraju 2D grafičke aplikacije zasnovane na biblioteci klasa Java 2D; - kreiraju 3D grafičke aplikacije zasnovane na biblioteci funkcija OpenGL.','','','Predavanja i auditorne vežbe se drže uz elektronske prezentacije. Na predavanjima se uvode teorijski koncepti, dok se na auditornim i laboratorijskim vežbama uvežbava primena algoritama i korišćenje široko rasprostranjenih paketa za pisanje grafičkih aplikacija. Studenti samostalno izrađuju 2 projekta (jedan iz 2D, drugi iz 3D grafike).',1,1,1,'2021-02-14 20:11:13','2021-02-14 20:11:13');
INSERT INTO `subjects` VALUES (41,'13E114SAB','Softverski alati baza podataka',1,8,6,2,2,2,1,'Uvođenje u softverske alate za razvoj baza podataka. Uvođenje u softverske alate za održavanje i korišćenje baza podataka. Uvođenje u programsko okruženje za baze podataka.','Znanje u vezi korišćenja softverskih alata za razvoj baza podataka. Znanje u vezi korišćenja softverskih alata za održavanje i korišćenje baza podataka. Znanje u vezi programskog okruženja za baze podataka.','','','',1,1,1,'2021-02-14 20:11:56','2021-02-14 20:11:56');
INSERT INTO `subjects` VALUES (42,'13E112OOP','Objektno orijentisano programiranje',3,3,5,2,2,2,1,'Upoznati studente sa osnovnim konceptima objektne paradigme. Osposobiti studente za projektovanje i pisanje programa na objektno orijentisanim programskim jezicima. Naučiti jezik C++. Upoznati studente sa osnovnim konceptima i idejama objektnog modelovanja na jeziku UML i projektnim obrascima.','Sposobnost razumevanja semantike koda pisanog na jeziku C++. Sposobnost rešavanja programerskih zadataka (pisanja koda) prema zadatim zahtevima korišćenjem objektnih koncepata i jezika C++. Sposobnost samostalnog projektovanja delova objektnog softvera manje složenosti.','','','Predavanja (30 časova), auditorne vežbe (30 časova). Samostalna izrada projekta: implementacija specifikovanog softverskog sistema na jeziku C++. Zahteva oko 60 sati individualnog učenja i vežbanja i oko 60 sati individualnog rada na projektu (uključujući i programiranje).',1,1,1,'2021-02-14 20:14:20','2021-02-14 20:14:20');
INSERT INTO `subjects` VALUES (43,'13E113AOR','Arhitektura i organizacija računara',3,5,6,2,3,2,1,'Upoznavanje sa strukturom računara, elementima arhitekture i organizacije procesora, i strukturom magistrale, ulazno/izlaznog sistema, i memorijskog sistema.','Po završetku kursa studenti će biti sposobni da razumeju: strukturu računara; elemente arhitekture i organizacije računara, strukturu magistrale, ulazno/izlaznog sistema, i memorijskog sistema.','','','',1,1,1,'2021-02-14 20:16:02','2021-02-14 20:16:02');
INSERT INTO `subjects` VALUES (44,'13E114IP','Internet programiranje',3,7,6,2,3,1,1,'Cilj nastave je osposobljavanje studenata da projektuju i pišu savremene Internet aplikacije koristeći osnovne elemente programskog jezika PHP. Upoznavanje studenata sa načinima realizacije kompleksnih klijentskih Veb stranica. Realizacija Veb stranica pomoću HTML i JavaScript programskog jezika, uz korišćenje naprednih tehnika.\n','Na kraju odslušanog predmeta studenti će biti osposobljeni da uz pomoć savremenog razvojnog okruženja razviju komercijalne Internet aplikacije zasnovane na PHP programskom jeziku. Biće kompetentni da dizajniraju troslojnu Internet aplikaciju i postave je na Internet.\n','','','',1,1,1,'2021-02-14 20:23:21','2021-02-14 20:23:21');
INSERT INTO `subjects` VALUES (45,'13E112OR','Organizacija računara',3,3,5,2,2,2,1,'Upoznavanje sa strukturom računara, elementima arhitekture i organizacije procesora, i strukturom magistrale, ulazno/izlaznog sistema, i memorijskog sistema.','Po završetku kursa studenti će biti sposobni da razumeju: strukturu računara; elemente arhitekture i organizacije računara, strukturu magistrale, ulazno/izlaznog sistema, i memorijskog sistema.','','','',1,1,1,'2021-02-14 20:31:23','2021-02-14 20:31:23');
INSERT INTO `subjects` VALUES (46,'13E112POR','Praktikum iz organizacije računara',3,3,3,2,0,0,2,'Upoznavanje sa elementima CICS i RISC arhitekture procesora i organizacije procesora bez i sa preklapanjem faza izvršavanja instrukcija.','Po završetku kursa studenti će biti sposobni da: razumeju CISC i RISC arhitekturu procesora; razumeju strukturu i funkcionisanje procesora bez i sa preklapanjem faza izvršavanja instrukcija; koriste literaturu radi daljeg izučavanja ovih oblasti.','','','',1,1,1,'2021-02-14 20:32:09','2021-02-14 20:32:09');
INSERT INTO `subjects` VALUES (47,'13E113BP','Baze podataka',3,6,6,2,2,2,1,'1. Upoznavanje studenata sa osnovnim pojmovima i principima Sistema za Upravljanje Bazama Podataka. 2. Upoznavanje sa osnovnim konceptima projektovanja baza podataka. 3. Osposobljavanje studenata za dizajn i implementaciju konkretne baze podataka i korišćenje komercijalnih sistema za upravljanje bazama podataka.','Osposobljenost studenata za dizajn i implementaciju konkretne baze podataka i korišćenje komercijalnih sistema za upravljanje bazama podataka.','','','30 časova predavanja + 30 časova vežbi na tabli sa rešavanjem zadataka + 15 časova laboratorijskih vežbi, kolokvijum na sredini semestra, projekat. Ukupno 75 časova samostalnog učenja i vežbanja, od čega 3 časa nedeljno tokom semestra i približno 30 časova pripreme u ispitnom roku.',1,1,1,'2021-02-14 20:33:22','2021-02-14 20:33:22');
INSERT INTO `subjects` VALUES (49,'13E111P1','Programiranje 1',1,1,5,1,3,2,0,'Učenje imperativnog programiranja na jezicima niskog nivoa i višim programskim jezicima. Prikaz internog predstavljanja podataka, sintakse i semantike, kontrolnih struktura, modularnog programiranja i analize kompleksnosti. Osposobljavanje studenata za konstrukciju, implementaciju i testiranje algoritama uz korišćenje statičkih i dinamičkih struktura podataka na proceduralnom programskom jeziku.','Studenti će biti u stanju da: transformišu izraze Bulove algebre, izračunaju vrednost broja na osnovu prikaza u komplementu dvojke i računaju sa ovakvim brojevima, napišu jednostavan program na simboličkom mašinskom jeziku picoComputer-a, razumeju sintaksne definicije, razvijaju, isprave i testiraju modularne strukturirane programe na višem programskom jeziku i procene njihovu kompleksnost.','P1 Sreda 12:00\nP2 Sreda 14:00','V1 Petak 12:00\nV2 Petak 14:00','',0,1,1,'2021-02-20 18:33:20','2021-02-26 11:27:08');
INSERT INTO `subjects` VALUES (50,'13E111PKR','Praktikum iz korišćenja računara',1,1,2,2,1,0,1,'Upoznavanje studenata sa osnovnim elementima personalnih računara sa aspekta korisnika, kao i upućivanje u korišćenje operativnog sistema za personalne računare Microsoft Windows, Interneta i njegovih osnovnih usluga, softverskog paketa Microsoft Office. Osposobljavanje studenata za samostalno istraživanje i proučavanje navedenih paketa i njihovo korišćenje u praksi.','Nakon završenog kursa student je osposobljen da realizuje i formatira osnovne tipove dokumenata, kao što su tekstualni, tabelarna izračunavanja, vizuelne prezentacije. Takođe, studenti će biti osposobljeni da na efikasan način koriste osnovne servise Interneta','','','',1,1,1,'2021-02-20 18:34:43','2021-02-20 18:34:43');
INSERT INTO `subjects` VALUES (51,'13M111SON','Sistemi otporni na otkaze',4,9,6,2,2,2,0,'Učenje hardverskih i softverskih mehanizama i tehnika smanjenja osetljivosti na otkaze i osposobljavanje studenata da modeliraju, projektuju i vrednuju takve sisteme.','Ovladavanje metodologijom i tehnikama modeliranja, projektovanja i vrednovanja sistema sa smanjenom osetljivošću na otkaze.','','','Uslov: Arhitektura i organizacija računara 1 i 2, Operativni sistemi 1 i 2, Programski jezici 1 i 2, Računarske mreže',1,1,1,'2021-02-24 20:12:25','2021-02-24 20:12:25');
INSERT INTO `subjects` VALUES (52,'13M111PSZ','Pronalaženje skrivenog znanja',4,9,6,2,2,2,0,'Upoznati studente sa osnovnim pojmovima i principima mašinskog učenja, data mining-a, tehnologijama Semantičkog Veba, kao i modelovanja koncepata. Upoznati studente sa principima projektovanja i implementacije data mining modela i ontologija Semantičkog Veba.','Studenti će biti u stanju da razumeju kako se znanje i podaci konceptualizuju, organizuju, dohvataju, pretražuju i smeštaju. Takođe, posedovaće znanje o mašinskom učenju, data mining-u, Semantičkim Veb tehnologijama i modelovanju koncepata.\n','','','Uslov: Baze podataka 1, Ekspertski sistemi',1,1,1,'2021-02-24 20:13:13','2021-02-24 20:13:13');
INSERT INTO `subjects` VALUES (53,'13M111RBM','Računarstvo u bio-medicini',4,9,6,2,2,2,0,'Zbližavanje sa primenama informatike u medicini kroz pregled upotrebe u raznim oblastima zdravstva; upoznavanje sa konceptima, relevantnim standardima i problemima koji se javljaju u praksi.\n','Sticanje sveobuhvatnog pregleda oblasti medicinske informatike uz dobijanje polaznih informacija potrebnih za produbljivanje i praktičnu primenu znanja u pojedinačnim podoblastima.\n','','','',1,1,1,'2021-02-24 20:13:46','2021-02-24 20:13:46');
INSERT INTO `subjects` VALUES (54,'13M111PUS','Programiranje ugrađenih sistema',4,9,6,2,2,2,1,'Razumevanje arhitektura modernih ugrađenih sistema. Razumevanje i ovladavanje tehnikama prilagođavanja namenskih operativnih sistema. Analiza bitnih karakteristika ugrađenih sistema. Sticanje veštine razvoja drajvera za namenske operativne sisteme. Sticanje veštine razvoja aplikacija za ugrađene sisteme.\n','Po uspešno savladanom predmetu, studenti će biti osposobljeni da: - analiziraju i razumeju dokumentaciju hardverskih komponenata ugrađenih sistema, - prilagode postojeće operativne sisteme otvorenog koda namenskim uređajima, - prošire namenski operativni sistem razvojem novih pokretača uređaja (drajvera), u cilju dodavanja novih komponenata, - razviju aplikaciju za namenski operativni sistem koja kroz odgovarajući API intereaguje sa hardverskim komponentama, - da sprovedu analizu razvijenog sistema u cilju uočavanja i otklanjanja potencijalnih nedostataka.\n','','','Nema formalnog uslova. Potrebna predznanja iz oblasti Arhitekture računara, Operativnih sistema, Programiranja na asembleru, Programiranja u jezicima C, C++, Sistemskog programiranja i Mikroprocesorskih sistema.\n',1,1,1,'2021-02-24 20:14:24','2021-02-24 20:14:24');
INSERT INTO `subjects` VALUES (55,'13E114PS','Projektovanje softvera',4,9,6,2,2,2,1,'Razumevanje i ovladavanje konceptima modeliranja i projektovanja softvera korišćenjem projektnih uzoraka. Učenje standardne grafičke notacije za modeliranje UML kroz 13 vrsta dijagrama, kao i najčešće korišćenih projektnih uzorka strukture, ponašanja i kreiranja.\n','Student poznaje koncepte modeliranja i projektovanja softvera. Student je sposoban je da modelira složene softverske sisteme koristeći standardni jezik UML 2. Student pri projektovanju softvera ume da prepozna uslove za primenu i da primeni adekvatne projektne uzorke iz GoF kataloga projektnih uzoraka.\n','','','Ne postoji formalan uslov, ali je očekivano da student poznaje gradivo kursa IR2OO2.\n',1,1,1,'2021-02-24 20:15:09','2021-02-24 20:15:09');
INSERT INTO `subjects` VALUES (56,'13E113OS2','Operativni sistemi 2',4,9,6,2,2,2,1,'Upoznati studente sa širim spektrom složenijih i naprednijih koncepata i principa konstrukcije operativnih sistema. Obezbediti napredna znanja o konceptima, algoritmima, principima, problemima i rešenjima vezanim za operativne sisteme uopšte. Upoznati se sa principima konstrukcije konkretnih, realnih operativnih sistema\n','Poznavanje opštih principa rada, konstrukcije i implementacije operativnih sistema uopšte. Poznavanje naprednijih koncepata i algoritama. Poznavanje nekih delova i rešenja iz konkretnih popularnih operativnih sistema opšte namene.\n','','','',1,1,1,'2021-02-24 20:17:20','2021-02-24 20:17:20');
INSERT INTO `subjects` VALUES (57,'13E114IS','Inteligentni sistemi',4,9,6,2,2,2,1,'Upoznavanje studenata sa osnovnim konceptima i tehnikama veštačke inteligencije i ekspertskih sistema. Tokom kursa studenti će izučavati najpopularnije modele implementacije ovakvih vrsta aplikacija.\n','Studenti će biti osposobljeni da prepoznaju problem koji pripada oblasti veštačke inteligencije i ekspertskih sistema i da na osnovu svog znanja primene najpodesniju i najefikasniju metodu za njegovo rešavanje.\n','','','',1,1,1,'2021-02-24 20:18:01','2021-02-24 20:18:01');
INSERT INTO `subjects` VALUES (58,'13E114RM2','Računarske mreže 2',4,9,6,2,2,2,1,'Upoznavanje studenata sa arhitekturom i mehanizmima funkcionisanja Interneta, te naprednim konceptima, protokolima i algoritmima funkcionisanja nekih ključnih Internet servisa i savremenih računarskih mreža.\n','Nakon ovog kursa studenti će u potpunosti razumeti arhitekturu Interneta i modernih mehanizama prosleđivanja paketa. Biće sposobni da samostalno odrede politiku rutiranja i da je implementiraju na realnim mrežnim uređajima. Takođe, kroz učenje o mehanizmima upraljanja uređajima i različitim Internet protokolima biće u stanju da dizajniraju efikasne servise zasnovane na modernim mrežnim tehnologijama.\n','','','',1,1,1,'2021-02-24 20:18:48','2021-02-24 20:18:48');
INSERT INTO `subjects` VALUES (59,'13M111SIP','Sociološki i profesionalni aspekti računarstva',4,10,6,2,2,2,0,'Upoznavanje studenata sa problemima i izazovima sa kojima se suočavaju računarski profesionalci i korisnici računara u savremenom društvu. Sagledavanje socijalnih, pravnih i etičkih aspekata profesije, kao i njenog istorijskog razvoja i potencijala za budućnost. Isticanje značaja netehničkih aspekta profesije i uticaja uvođenja novih hardverskih i softverskih proizvoda na društvo, grupe i pojedince.\n','Studenti će biti u stanju da: identifikuju značajne, kontinuirane trendove u istoriji računarstva, razumeju doprinos pojedinih naučnika iz ove oblasti, procene društvene promene nastale upotrebom računara, zaštite privatnosti i suprotstave se socijalnom inženjeringu, razumeju posledice softverske piraterije, napišu pravilnik o politici sigurnosti u kompaniji, usvoje kodeks profesionalne etike.\n','','','',1,1,1,'2021-02-24 20:20:25','2021-02-24 20:20:25');
INSERT INTO `subjects` VALUES (60,'13M111PRV','Programiranje u realnom vremenu',4,10,6,1,2,2,0,'Steći teorijsko znanje i praktične veštine potrebne za analizu, projektovanje i implementaciju softverskih sistema za rad u realnom vremenu (RT). Steći opšte, fundamentalno znanje primenjivo na RT sisteme uopšte. Osposobiti se za razumevanje postojećih i projektovanje sopstvenih specijalizovanih RT sistema','Poznavanje osnovnih koncepata i principa sistema za rad u realnom vremenu. Sposobnost analize, projektovanja i realizacije softvera za ove sisteme. Poznavanje jezika i alata za projektovanje ovih sistema (uključujući jezike Ada i RT Java)\n','','','',1,1,1,'2021-02-25 08:00:36','2021-02-25 08:00:36');
INSERT INTO `subjects` VALUES (61,'13M111PRM','Projektovanje računarskih mreža',4,10,6,1,2,2,1,'Cilj je da se studenti obuče za samostalni praktičan rad na projektovanju računarskih mreža i konfigurisanju mrežnih uređaja.\n','Predmet nudi teorijsku osnovu i potrebno znanje za projektovanje računarskih mreža i rad na mrežnim uređajim. Savladavanjem znanja iz ovog predmeta kroz intenzivni rad na simulatoru računarskih mreža, studenti stiču praktičnu veštinu u konfigurisanju komunikacionih protokola i servisa na rešavanju konkretnog problema.\n','','','',1,1,1,'2021-02-25 08:01:10','2021-02-25 08:01:10');
INSERT INTO `subjects` VALUES (62,'13M111PP2','Programski prevodioci 2',4,10,6,1,2,2,1,'Studenti treba da steknu bolje razumevanje sledećih tema: raznovrsne tehnike parsiranja; otkrivanje grešaka i oporavak; predstavljanje međukoda; Optimizacija koda; upravljanje memorijom; generisanje koda.\n','Očekuje se da student po završetku kursa bude u stanju da: Demonstrira razumevanje, kritičku analizu i primenu važećih teorija, modela i tehnika iz oblasti konstrukcije programskih prevodilaca. Da bude sposoban da primeni naprednije alate za konstrukciju kompajlera i jezičkih procesora.\n','','','',1,1,1,'2021-02-25 08:01:45','2021-02-25 08:01:45');
INSERT INTO `subjects` VALUES (65,'13M111PSI','Principi softverskog inženjerstva',4,10,6,2,2,2,1,'Upoznavanje studenata sa osnovnim konceptima softverskog inženjerstva. Kurs obrađuje različite aspekte životnog ciklusa softvera: specifikaciju, dizajn, implementaciju, testiranje, održavanje, elekente upravljanja projektom. Student prolazi kroz praktičan projekat vezan za računarske oblake.','Očekuje se da student po završetku studija bude u stanju da: Demonstrira razumevanje, kritičku analizu i primenu važećih teorija, modela i tehnika iz oblasti softverskog inženjerstva. Da stekne osećaj za timski rad. Da razume tehnologiju računarskih oblaka i razvija aplikacije na njima.','','','',1,1,1,'2021-02-26 11:00:19','2021-02-26 11:00:19');
INSERT INTO `subjects` VALUES (66,'13M111GI','Genomska informatika',4,10,6,2,2,2,1,'U okviru ovog predmeta predstavljeni su osnovni metodi računarske analize podataka dobijenih iz genoma, sa ciljem izvođenja biološki značajnih zaključaka. Biće ukazano na prednosti i mane ovih metoda i na značajne parametre koji utiču na rezultate ovih analiza.','Studenti će razumeti principe dizajna algoritama za obradu bioloških podataka i kako oni rade. Biće sposobni da analiziraju probleme i primene odgovarajuće metode.','','','',1,1,1,'2021-02-26 11:00:55','2021-02-26 11:00:55');
INSERT INTO `subjects` VALUES (67,'13M111ZRM','Zaštita računarskih sistema i mreža',4,10,6,2,2,2,1,'Upoznavanje studenata sa oblašću prevencije upada u računarske sisteme i mreže. Obuka studenata za obavljanje poslova iz oblasti zaštite računarskih sistema i mreža i etičkog upada u sisteme. Razumevanje pretnji i vektora napada na računarske i softverske sisteme. Praktičan rad studenata na većem broju alata za analizu i detekciju napada.','Očekuje se da student koji završi ovaj kurs može da: * razume i poznaje metodologiju upada u računarske sisteme i mreže * poznaje različite vrste napada na računarske sisteme i mreže * aktivno koristi veći broj alata za detekciju i analizu pretnji i napada na računarske sisteme i mreže * izvrši etičke upade u računarske sisteme i mreže kao metodu analize ranjivosti','','','',1,1,1,'2021-02-26 11:02:24','2021-02-26 11:02:24');
INSERT INTO `subjects` VALUES (68,'13S111P1','Programiranje 1',2,1,5,1,3,2,0,'Učenje imperativnog programiranja na jezicima niskog nivoa i višim programskim jezicima. Prikaz internog predstavljanja podataka, sintakse i semantike,tipova, kontrolnih struktura, modularnog programiranja i analize kompleksnosti. Osposobljavanje studenata za razvoj, implementaciju i testiranje algoritama uz korišćenje statičkih i dinamičkih struktura podataka na proceduralnom programskom jeziku.\n','Studenti će biti u stanju da: transformišu izraze Bulove algebre, izračunaju vrednost broja na osnovu prikaza u komplementu dvojke i računaju sa ovakvim brojevima, napišu jednostavan program na simboličkom mašinskom jeziku picoComputer-a, razumeju sintaksne definicije, razvijaju, isprave i testiraju modularne strukturirane programe na višem programskom jeziku i procene njihovu kompleksnost.\n','','','',1,1,1,'2021-02-26 11:04:51','2021-02-26 11:04:51');
INSERT INTO `subjects` VALUES (69,'13S111PP1','Praktikum iz programiranja 1',2,1,3,1,0,0,2,'Osnovna namena Praktikuma je upoznavanje studenata sa kompletnim procesom razvoja programa i osposobljavanje za samostalan rad u konkretnom razvojnom okruženju. Ovako koncipiran, predmet ima za cilj da obradi i praktično nauči studente praktičnoj primeni svega onoga što su imali prilike da čuju na nastavi iz predmeta Programiranje 1.\n','Znanje osnovnih koncepata rada sa razvojnim okruženjima (izvršavanje programa korak po korak, praćenje trenutnog sadržaja promenljivih, preusmeravanje ulaza i izlaza), iz čega sledi osposobljenost za samostalno rešavanje programskih problema male ili srednje složenosti na računaru. Praktična primena svega naučenog u okviru predmeta Programiranje 1.\n','','','',1,1,1,'2021-02-26 11:05:29','2021-02-26 11:05:29');
INSERT INTO `subjects` VALUES (70,'13S111PKR','Praktikum iz korišćenja računara',2,1,2,2,1,0,1,'Upoznavanje studenata sa osnovnim elementima personalnih računara sa aspekta korisnika, kao i upućivanje u korišćenje operativnog sistema za personalne računare Microsoft Windows, Interneta i njegovih osnovnih usluga, softverskog paketa Microsoft Office. Osposobljavanje studenata za samostalno istraživanje i proučavanje navedenih paketa i njihovo korišćenje u praksi.\n','Nakon završenog kursa student je osposobljen da realizuje i formatira osnovne tipove dokumenata, kao što su tekstualni, tabelarna izračunavanja, vizuelne prezentacije. Takođe, studenti će biti osposobljeni da na efikasan način koriste osnovne servise Interneta\n','','','',1,1,1,'2021-02-26 11:06:01','2021-02-26 11:06:01');
INSERT INTO `subjects` VALUES (71,'13S111P2','Programiranje 2',2,2,5,1,3,2,0,'Upoznavanje sa sintaksom i semantikom programskog jezika C. Primena naprednih koncepata proceduralnog programiranja u jeziku C. Osposobljavanje studenata za konstrukciju algoritama, korišćenje statičkih i dinamičkih struktura podataka, implementaciju i testiranje programa u programskom jeziku C.\n','Studenti će biti u stanju da: izračunaju vrednost realnog broja na osnovu prikaza po IEEE standardu i da računaju sa ovakvim brojevima, napišu složenije programe na jeziku C koji koriste operatore, kontrolne strukture i bibliotečke funkcije, upotrebe makroprocesorske direktive, kao i da razvijaju, testiraju i nadograđuju modularne programe koji koriste ulančane liste, stabla i datoteke.\n','','','',1,1,1,'2021-02-26 11:06:50','2021-02-26 11:13:27');
INSERT INTO `subjects` VALUES (72,'13S111ASP1','Algoritmi i strukture podataka 1',2,2,5,1,2,2,1,'Upoznavanje sa logičkom organizacijom i memorijskom reprezentacijom linearnih i nelinearih struktura podataka, osnovnim operacijama i tipičnim primenama ovih struktura.\n','Ovaj predmet treba studenta da osposobi za programsku implementaciju linearnih i nelineranih struktura, kao i algoritama za rad sa njima u tipičnim primenama.\n','','','',1,1,1,'2021-02-26 11:08:03','2021-02-26 11:08:03');
INSERT INTO `subjects` VALUES (73,'13S111ORT1','Osnovi računarske tehnike 1',2,2,5,1,3,2,0,'Upoznavanje sa Bulovom algebrom, prekidačkim funkcijama, kombinacionim i sekvencijalnim prekidačkim mrežama, logičkim i memorijskim elementima, standardnim kombinacionim i sekcencijalnim modulima i njihovim korišćenjem kod projektovanja digitalnih uređaja.\n','Po završetku kursa studenti će biti sposobni da: razumeju strukturu prekidačkih mreža; obavljaju analizu i sintezu kombinacionih i sekvencijalnih mreža; koriste kombinacione i sekvencijalne module i projektuju digitalne uređaje manje složenosti.\n','','','',1,1,1,'2021-02-26 11:08:35','2021-02-26 11:08:35');
INSERT INTO `subjects` VALUES (74,'13S111PORT','Praktikum iz osnova računarske tehnike',2,2,3,1,0,0,2,'Upoznavanje studenata sa osnovnim kombinacionim i sekvencijalnim elementima. Razumevanje strukture i funkcionisanja prekidačkih mreža. Realizacija složenih prekidačkih mreža pomoću konfigurabilnog hardvera i vizuelnog simulatora.\n','Po završetku kursa studenti će biti sposobni da: razumeju strukturu prekidačkih mreža; obavljaju analizu i sintezu kombinacionih i sekvencijalnih mreža; koriste kombinacione i sekvencijalne module.\n','','','',1,1,1,'2021-02-26 11:09:11','2021-02-26 11:09:11');
INSERT INTO `subjects` VALUES (75,'13S111PP2','Praktikum iz programiranja 2',2,2,3,1,0,0,2,'Osnovna namena Praktikuma je upoznavanje studenata sa kompletnim procesom razvoja programa i osposobljavanje za samostalan rad u konkretnom razvojnom okruženju. Ovako koncipiran, predmet ima za cilj da obradi i praktično nauči studente svemu onome što su imali prilike da čuju na nastavi iz predmeta Programiranje 2.\n','Znanje osnovnih koncepata rada sa razvojnim okruženjima (izvršavanje programa korak po korak, praćenje trenutnog sadržaja promenljivih, preusmeravanje ulaza i izlaza), iz čega sledi osposobljenost za samostalno rešavanje programskih problema male ili srednje složenosti. Praktična primena naučenog iz predmeta Programiranje 2.\n','','','',1,1,1,'2021-02-26 11:09:31','2021-02-26 11:09:31');
/*!40000 ALTER TABLE `subjects` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2021-02-26 14:49:23
